import { Product } from '@/types';

const getImageUrl = (localPath?: string, fallback?: string) => {
  if (localPath && localPath.startsWith('/')) return localPath;
  return fallback || 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=600&h=800&fit=crop&q=80';
};

const JERSEY_PLACEHOLDER = '/images/products/jersey-placeholder.jpg';
const BIB_PLACEHOLDER = '/images/products/bib-placeholder.jpg';

export const staticProducts: Product[] = [
  { id: '1', name: 'Ineos Grenadiers 2024 Race Jersey', team: 'Ineos Grenadiers', category: 'jersey', year: 2024, condition: 'new', price: 249.99, originalPrice: 299.99, image: '/images/products/1-1768933412769.png', images: ['/images/products/1-1768933412769.png', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=800&fit=crop&q=80&auto=format'], description: 'Authentic 2024 Ineos Grenadiers race jersey worn by the team. Premium materials with advanced moisture-wicking technology.', size: 'M', inStock: true, featured: true, tour: 'world-tour' },
  { id: '2', name: 'Jumbo-Visma 2023 Yellow Jersey', team: 'Jumbo-Visma', category: 'jersey', year: 2023, condition: 'excellent', price: 349.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Rare 2023 Tour de France yellow jersey from Jumbo-Visma. Limited edition collectible.', size: 'L', inStock: true, featured: true, tour: 'world-tour' },
  { id: '3', name: 'UAE Team Emirates 2024 Bib Shorts', team: 'UAE Team Emirates', category: 'bibs', year: 2024, condition: 'like-new', price: 199.99, originalPrice: 249.99, image: BIB_PLACEHOLDER, images: [BIB_PLACEHOLDER], description: 'Professional-grade bib shorts with premium chamois and compression technology.', size: 'M', inStock: true, featured: false, tour: 'world-tour' },
  { id: '4', name: 'Quick-Step Alpha Vinyl 2023 Jersey', team: 'Quick-Step Alpha Vinyl', category: 'jersey', year: 2023, condition: 'excellent', price: 179.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Classic Quick-Step jersey from their final season. Authentic team issue.', size: 'S', inStock: true, featured: false, tour: 'world-tour' },
  { id: '5', name: 'EF Education-EasyPost 2024 Gloves', team: 'EF Education-EasyPost', category: 'gloves', year: 2024, condition: 'new', price: 49.99, image: getImageUrl(undefined, 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=800&fit=crop&q=80'), images: [getImageUrl(undefined, 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=800&fit=crop&q=80')], description: 'Professional cycling gloves with gel padding and breathable mesh.', size: 'M', inStock: true, featured: false, tour: 'world-tour' },
  { id: '6', name: 'Movistar Team 2024 Socks', team: 'Movistar', category: 'socks', year: 2024, condition: 'new', price: 24.99, image: getImageUrl(undefined, 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=800&fit=crop&q=80'), images: [getImageUrl(undefined, 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=800&fit=crop&q=80')], description: 'Official team socks with compression technology and moisture-wicking fabric.', size: 'One Size', inStock: true, featured: false, tour: 'world-tour' },
  { id: '7', name: 'Bora-Hansgrohe 2023 Race Jersey', team: 'Bora-Hansgrohe', category: 'jersey', year: 2023, condition: 'good', price: 149.99, originalPrice: 199.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Authentic race jersey with minor wear. Still in great condition.', size: 'L', inStock: true, featured: false, tour: 'world-tour' },
  { id: '8', name: 'Team DSM 2024 Bib Shorts', team: 'Team DSM', category: 'bibs', year: 2024, condition: 'like-new', price: 189.99, image: BIB_PLACEHOLDER, images: [BIB_PLACEHOLDER], description: 'Professional bib shorts with premium Italian chamois.', size: 'M', inStock: true, featured: false, tour: 'world-tour' },
  { id: '9', name: 'Trek-Segafredo 2024 Race Jersey', team: 'Trek-Segafredo', category: 'jersey', year: 2024, condition: 'new', price: 229.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Authentic 2024 Trek-Segafredo race jersey. Premium quality and perfect condition.', size: 'M', inStock: true, featured: false, tour: 'world-tour' },
  { id: '10', name: 'AG2R Citroën 2023 Jersey', team: 'AG2R Citroën', category: 'jersey', year: 2023, condition: 'excellent', price: 199.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Classic AG2R Citroën jersey from 2023 season. Authentic team issue.', size: 'L', inStock: true, featured: false, tour: 'world-tour' },
  { id: '11', name: 'Lotto Dstny 2024 Jersey', team: 'Lotto Dstny', category: 'jersey', year: 2024, condition: 'new', price: 189.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Authentic 2024 Lotto Dstny race jersey. Brand new with tags.', size: 'S', inStock: true, featured: false, tour: 'world-tour' },
  { id: '12', name: 'Cofidis 2023 Race Jersey', team: 'Cofidis', category: 'jersey', year: 2023, condition: 'excellent', price: 169.99, image: JERSEY_PLACEHOLDER, images: [JERSEY_PLACEHOLDER], description: 'Authentic Cofidis race jersey from 2023 season. Excellent condition.', size: 'M', inStock: true, featured: false, tour: 'world-tour' },
];
